# @name get-prompts

GET http://localhost:3333/prompts

### 

# @name upload-file
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="noticia2.mp3"
Content-Type: audio/mpeg

< ./noticia.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name crate-transcription
POST http://localhost:3333/videos/b22e61e0-92cb-4e7e-a205-9d7eca0ffd61/transcription
Content-Type: application/json

 {
  "prompt":"cavalo, tonel,campeonato"
 }

###

# @name crate-description
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "b22e61e0-92cb-4e7e-a205-9d7eca0ffd61",
  "temperature": 0.2,
	"template": "Gere um resumo sucinto da transcrição do video informada a seguir: '''{transcription}'''"
}
